name: HBFav-Android
markdown: redcarpet
pygments: true
baseurl: /HBFav-Android

market_link: https://play.google.com/store/apps/details?id=com.hbfav.android

sass:
  style: expanded
  deploy_style: compressed
  compile_in_place: true
